project:
  type: website

execute:
  echo: false
  warning: false

website:
  title: "Myositis ILD"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Overview"
        contents:
          - index.qmd
          - longitudinal_report.qmd
          - stable_ild.qmd
          - bleeds_on_hand.qmd
          - who_has_pfts.qmd
          - clinical_data.qmd
          - undefined_antibody.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
